### ISSUE TITLE
Creating a game and joining a different game causes a crash

### ISSUE THREAD

**Issue by nschulzke** [cs340tabyu/cs340Winter2018#119]
Steps to reproduce:

1. Join a game
2. Leave the game
3. Join the game again

The game then crashes.

Stacktrace:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                at java.lang.Thread.run(Thread.java:764)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean byu.cs340.main.results.JoinGameResult.isPassed()' on a null object reference
                                                                                at byu.cs340.tickettorideclient.presenters.GameListPresenter.joinGame(GameListPresenter.java:85)
                                                                                at byu.cs340.tickettorideclient.views.GameListFragment$JoinGameTask.doInBackground(GameListFragment.java:260)
                                                                                at byu.cs340.tickettorideclient.views.GameListFragment$JoinGameTask.doInBackground(GameListFragment.java:256)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by edenknudson** [comment]
It isn't part of the spec to be able to leave and join another game, so we just got rid of the option.
