### ISSUE TITLE
Crash when starting a 4-player game

### ISSUE THREAD

**Issue by nschulzke** [cs340tabyu/cs340Winter2018#193]
The first time we started a game with four players it worked, but twice now it's broken with this error for three of them after they select destination cards. This stacktrace was on the server, and the client got a null response. The fourth player in each case (not the same player #) worked.

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at byu.cs340.main.commands.ClientCommand.execute(ClientCommand.java:76)
        at byu.cs340.main.handlers.GenericHandler.handle(GenericHandler.java:31)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.handle(Unknown Source)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Unknown Source)
        at byu.cs340.main.models.Game.getRandomDestCard(Game.java:551)
        at byu.cs340.main.models.Game.giveDestCardChoices(Game.java:582)
        at byu.cs340.main.models.Game.drawDestCards(Game.java:537)
        at byu.cs340.main.server_facade.ServerFacade.drawDestCards(ServerFacade.java:296)
        ... 16 more
```

**Comment by edenknudson** [comment]
We fixed that.
