### ISSUE TITLE
app crashed when I clicked the map

### ISSUE THREAD

**Issue by abguymon** [cs340tabyu/cs340Winter2018#43]
I don't really know why it happened but this is the stack trace:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.trevinavery.tickettoride, PID: 4039
                  java.lang.IllegalArgumentException: y must be < bitmap.height()
                      at android.graphics.Bitmap.checkPixelAccess(Bitmap.java:1451)
                      at android.graphics.Bitmap.getPixel(Bitmap.java:1400)
                      at com.trevinavery.tickettoride.game.GameMapFragment$2.onTouch(GameMapFragment.java:113)
                      at android.view.View.dispatchTouchEvent(View.java:9939)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
                      at android.view.View.dispatchPointerEvent(View.java:10163)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:323)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by TrevinAvery** [comment]
@abguymon We need a little more information please.
1. Do you know where you clicked?
2. Was it your turn? Was something else open?
3. Were you using a Nexus 5 as your emulator, or something else?

**Comment by TrevinAvery** [comment]
Unable to recreate. But we added an if statement to make sure we only request pixels that are within the size of the image.
